version: '3.8'

services:
  frontend:
    env_file:
      - ./frontend/.env
    build: ./frontend
    container_name: frontend
    image: assessment/frontend:1.0.0
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - VITE_API_BASE_URL=http://localhost:5001/api
      - PORT=3000
    stdin_open: true
    tty: true

  backend:
    build: ./backend
    container_name: node-app
    image: assessment/node-app:1.0.0
    ports:
      - '5001:5001'
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/nokiaaiims
      - PORT=5001
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=nokiaaiims

volumes:
  mongo-data:
